"""
🔧 Configuration Hub for REALISTA
==================================

Think of this file as the "control panel" for the entire project.
Every model path, API key, and magic number lives here — so you
never have to hunt through the codebase to change a setting.

Everything can be overridden via environment variables or a `.env` file,
so your secrets stay out of version control.
"""
import os
from dotenv import load_dotenv

# ┌──────────────────────────────────────────────────────────────────┐
# │  Load .env file (if it exists) for machine-specific overrides   │
# │  e.g.  OPENAI_API_KEY=sk-...                                   │
# │  This way, you never need to hard-code secrets here.            │
# └──────────────────────────────────────────────────────────────────┘
load_dotenv()


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  OpenAI API — needed for LLM judges and reasoning model targets
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

OPENAI_API_KEY: str = os.environ.get("OPENAI_API_KEY", "")

# These are the specific model versions the paper uses for evaluation.
# The "judges" decide if an attack is realistic and if the LLM hallucinated.
GPT_5_NANO = "gpt-5-nano-2025-08-07"
GPT_5_MINI = "gpt-5-mini-2025-08-07"
FEASIBILITY_CHECKER_MODEL = "gpt-4.1-mini-2025-04-14"     # Checks: "Is the rephrased question equivalent?"
HALLUCINATION_EVALUATOR_MODEL = "gpt-4.1-2025-04-14"       # Checks: "Did the LLM hallucinate?"

# When attacking reasoning models (like GPT-5), we send prompts to these.
REASONING_TARGET_MODEL_MAP = {
    "gpt_5_nano": GPT_5_NANO,
    "gpt_5_mini": GPT_5_MINI,
}


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  Target LLMs — the open-source models we're trying to fool
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# Map from our short names → HuggingFace model IDs.
# If you've already downloaded a model locally, just swap the path here.
MODEL_REGISTRY = {
    "llama3_3b":   "meta-llama/Llama-3.2-3B-Instruct",     # ~7 GB VRAM
    "llama3_8b":   "meta-llama/Llama-3.1-8B-Instruct",     # ~16 GB VRAM
    "qwen2_5_7b":  "Qwen/Qwen2.5-7B-Instruct",            # ~14 GB VRAM
    "qwen2_5_14b": "Qwen/Qwen2.5-14B-Instruct",           # ~28 GB VRAM
}


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  Layer Selection — which transformer layer to extract latents from
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# The paper operates on hidden states from an early transformer block
# (layer 3). Why early? Because later layers are too specialized for
# next-token prediction — early layers capture more "semantic" info
# that's useful for meaning-preserving edits.
LAYER_NUM_REGISTRY = {
    "llama3_3b":   3,
    "llama3_8b":   3,
    "qwen2_5_7b":  3,
    "qwen2_5_14b": 3,
}


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  Dataset — the questions we test on
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# We use a 347-question MMLU subset (same as the SECA paper) spanning
# 16 subjects, so our results are directly comparable to prior work.
MMLU_DATASET = "cais/mmlu"


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  Dictionary Paths — where pre-computed attack data lives
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# Rephrasing prompts: JSON files with "concept → rephrasings" per question.
# These were generated by prompting an LLM: "Rewrite this question in a
# more [concept] style."
REPHRASING_DICT_PATH = os.environ.get(
    "REALISTA_REPHRASING_PATH",
    os.path.join(os.path.dirname(__file__), "..", "data", "rephrasing_prompts"),
)

# Latent direction dictionaries: precomputed z^(i) = φ(rephrasing) - φ(original)
# vectors. These tell us "which direction to push in latent space to get
# a particular style of rephrasing."
LATENT_DICT_PATH = os.environ.get(
    "REALISTA_LATENT_DICT_PATH",
    os.path.join(os.path.dirname(__file__), "..", "data", "latent_dicts"),
)


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  Terminal Colors — because life's too short for plain text output
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

RED_BACKGROUND    = "\033[41m"    # For errors / infeasible results
GREEN_BACKGROUND  = "\033[42m"    # For success / feasible results
YELLOW_BACKGROUND = "\033[43m"    # For warnings
RESET             = "\033[0m"     # Back to normal
