"""
📖 Dictionary Loading — Pre-computed Attack Data
==================================================

REALISTA's attack relies on two pre-computed "dictionaries":

1. **Rephrasing Dictionary** (Stage 1)
   JSON files mapping each MMLU question to concept-based rephrasings.
   Example: question #0 → {"concise": ["short version 1", "short version 2"],
                            "formal": ["formal version 1", ...]}

2. **Latent Direction Dictionary** (Stage 2)
   Pickled tensors storing z^(i) = φ(rephrasing_i) − φ(original).
   Each direction tells us: "push the latent THIS way to get a more
   [concept]-like version of the question."

This module ONLY loads and reshapes these artifacts — it does NOT build
them. For building from scratch, see `optional_dict_construction/`.

Also provides `get_original_latent()` — the encoder φ that extracts
the latent representation z₀ from a chosen transformer layer.

     ┌──────────────┐        ┌──────────────────────────┐
     │  JSON file   │──────▸ │  load_rephrasing_prompts  │
     │  per subject │        │  Returns: dict of strings  │
     └──────────────┘        └──────────────────────────┘

     ┌──────────────┐        ┌──────────────────────────┐
     │  .pkl / .zst │──────▸ │  load_latent_dict         │
     │  per model   │        │  Returns: dict of tensors  │
     └──────────────┘        └──────────────────────────┘

     ┌──────────────┐        ┌──────────────────────────┐
     │  Question    │──────▸ │  get_original_latent      │
     │  text x₀     │        │  Returns: z₀ tensor       │
     └──────────────┘        └──────────────────────────┘
"""
import json
import os
import pickle

import torch
import torch.nn.functional as F
import zstandard
from tqdm import tqdm

from src.config import (
    MMLU_DATASET, LATENT_DICT_PATH, REPHRASING_DICT_PATH, LAYER_NUM_REGISTRY,
)

# The released latent dictionaries are compressed with zstd using a
# large window (--long=31 = up to 2 GiB window). The decompressor needs
# to be told to accept frames this large, or it'll refuse as a
# memory-safety precaution.
ZSTD_MAX_WINDOW_SIZE = 1 << 31  # 2 GiB


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  Stage 1: Rephrasing Dictionary (JSON)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def load_rephrasing_prompts(subject: str) -> dict:
    """Load the pre-computed rephrasings for one MMLU subject.

    Each file maps question indices to concept → rephrasing lists.
    These rephrasings were generated by prompting an LLM:
      "Rewrite this question in a more [concept] style."

    Parameters
    ----------
    subject : str  — e.g. "machine_learning", "anatomy"

    Returns
    -------
    dict — question_idx → {concept → [rephrasing1, rephrasing2, ...]}
    """
    path = os.path.join(REPHRASING_DICT_PATH, f"{subject}_rephrasings.json")

    if not os.path.isfile(path):
        raise FileNotFoundError(
            f"❌ No rephrasing dictionary found at:\n  {path}\n\n"
            "To fix this, either:\n"
            "  1. Download the data/ directory from the REALISTA repo, or\n"
            "  2. Set REALISTA_REPHRASING_PATH to the correct location."
        )

    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  Stage 2: Latent Direction Dictionary (Pickle / Compressed)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def load_latent_dict(model_type: str, mmlu_subject: str, verbose: bool = False):
    """Load pre-computed latent editing directions for Stage 2.

    These are tensors of shape [n_concepts, L, d_model] where each row is:
      z^(i) = φ(rephrasing_i) − φ(original_question)

    In plain English: each row tells us "if you want to make the question
    more [concept]-like, push the latent representation in THIS direction."

    Supports two file formats:
      - Plain pickle (.pkl) — fast to load
      - Zstd-compressed (.pkl.zst) — 10x smaller for distribution

    Parameters
    ----------
    model_type   : str  — e.g. "llama3_8b"
    mmlu_subject : str  — e.g. "machine_learning"
    verbose      : bool — print loading info

    Returns
    -------
    dict — question_idx → tensor of latent directions
    """
    layer_num = LAYER_NUM_REGISTRY[model_type]

    # Build the expected file path
    base_name = f"{model_type}_{mmlu_subject}_layer_{layer_num}_latent_dictionary.pkl"
    plain_path = f"{LATENT_DICT_PATH}/{model_type}/{mmlu_subject}/{base_name}"
    compressed_path = plain_path + ".zst"

    # Try plain pickle first (faster)
    if os.path.isfile(plain_path):
        if verbose:
            print(f"📂 Loading latent dictionary: {plain_path}")
        with open(plain_path, "rb") as f:
            return pickle.load(f)

    # Try zstd-compressed version
    elif os.path.isfile(compressed_path):
        if verbose:
            print(f"📦 Decompressing latent dictionary: {compressed_path}")
        decompressor = zstandard.ZstdDecompressor(
            max_window_size=ZSTD_MAX_WINDOW_SIZE,
        )
        with open(compressed_path, "rb") as fh:
            # Stream directly into pickle without writing decompressed bytes to disk
            with decompressor.stream_reader(fh) as reader:
                return pickle.load(reader)

    else:
        raise FileNotFoundError(
            f"❌ No latent dictionary found at:\n"
            f"  {plain_path}\n  {compressed_path}\n\n"
            "Download from the REALISTA HuggingFace release or set "
            "REALISTA_LATENT_DICT_PATH."
        )


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  Encoder φ: Extract Latent Representation z₀
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def get_original_latent(model, tokenizer, question_text: str, model_type: str):
    """Extract z₀ = φ(x₀) — the question's latent representation.

    How this works:
      1. Tokenize the question text into token IDs.
      2. Run a forward pass through the LLM with `output_hidden_states=True`.
      3. Grab the hidden state at layer 3 (an early residual-stream layer).

    Why layer 3?
      Early layers capture broad semantic information (meaning, topic)
      rather than the narrow next-token-prediction features of later layers.
      Editing at this level produces more meaningful, coherent rephrasings.

    Parameters
    ----------
    question_text : str   — the raw question (no prefix/suffix)
    model_type    : str   — used to look up which layer to extract from

    Returns
    -------
    z0 : Tensor [1, L, d_model]  — the question's latent at layer 3
    """
    layer_num = LAYER_NUM_REGISTRY[model_type]

    # Tokenize (no special tokens — we handle those in the prompt template)
    inputs = tokenizer(
        question_text, return_tensors="pt", add_special_tokens=False,
    ).to(model.device)

    # Forward pass — we need ALL hidden states, not just the final one
    with torch.no_grad():
        outputs = model(
            **inputs,
            output_hidden_states=True,  # This gives us every layer's output
            use_cache=False,
        )

    # hidden_states is a tuple of (n_layers + 1) tensors:
    #   index 0 = embedding output
    #   index 1 = after transformer block 0
    #   index 2 = after transformer block 1
    #   index 3 = after transformer block 2  ← we use this one
    #   ...
    z0 = outputs.hidden_states[layer_num].clone()

    return z0
